sudo: required
language: python
cache: pip
services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install molecule
  - pip install docker-py

env:
  matrix:
    - INSTANCE: centos-yourls-versioned
    - INSTANCE: centos-yourls-latest

script:
  - molecule converge -- --limit="localhost,${INSTANCE}"
